version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db_mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - mydata:/var/lib/mysql
    ports:
      - '9306:3306'
    environment:
      MYSQL_DATABASE: turnos
      MYSQL_ROOT_PASSWORD: examplePassword123
volumes:
  mydata:
      
